### ISSUE TITLE
? characters under "Between shadows and light"

### ISSUE THREAD

**Issue by ErdeiFarkasGyula** [Toma400/The_Isle_of_Ansur#20]
After copying the questionmark characters and pasting it as a text, it will be The Isle of Ansur but with an interesting font( 𝚃𝚑𝚎 𝙸𝚜𝚕𝚎 𝚘𝚏 𝙰𝚗𝚜𝚞𝚛 ). Unfortunately this kind of font won't load.
![image](https://user-images.githubusercontent.com/69863086/163574561-33c2e9be-aaba-4eae-a950-5d3a6af7c725.png)

**Comment by Toma400** [comment]
Yes, this issue is known, this is why I put on release notes that some characters may be "quirky". 
They work in my coding environment, but not on Windows terminals. They sadly don't support UTF-8 encoding, I put issue request in #14 but I'm yet not sure how to resolve it ^^' will try to fix it for next release
Thanks for report tho! Now I know it's not only me :D

**Comment by Toma400** [comment]
Fixed with commit of beautiful name acbdaaa :D
I switched all non-ASCII characters temporarily into ASCII ones, so no more fancy characters, but at least they won't be bugged.
In the meantime though, I will probably try to switch Windows terminal into a bit more modern terminal, like [cmder](https://cmder.net/).
